// <auto-generated />
namespace Semillitas.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addpaymentmethod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpaymentmethod));
        
        string IMigrationMetadata.Id
        {
            get { return "201708191152365_add-paymentmethod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
