// <auto-generated />
namespace Semillitas.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addenrollment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addenrollment));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180900156_add-enrollment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
